import { NumberValidator } from "../src"

describe("NumberValidator", () => {
    it("", () => {
        const isNumber = new NumberValidator().seal()
        expect(isNumber(null)).toBeFalsy()
        expect(isNumber(undefined)).toBeFalsy()
        expect(isNumber("123")).toBeFalsy()
        expect(isNumber(123)).toBeTruthy()
    })
    it("equals", () => {
        const isFortyTwo = new NumberValidator().equals(42).seal()
        expect(isFortyTwo("123")).toBeFalsy()
        expect(isFortyTwo(-Infinity)).toBeFalsy()
        expect(isFortyTwo(+Infinity)).toBeFalsy()
        expect(isFortyTwo(123)).toBeFalsy()
        expect(isFortyTwo(42.1)).toBeFalsy()
        expect(isFortyTwo(42)).toBeTruthy()
    })
    it("equalsNot", () => {
        const isNotOne = new NumberValidator().equalsNot(1).seal()
        expect(isNotOne("123")).toBeFalsy()
        expect(isNotOne(1)).toBeFalsy()
        expect(isNotOne(0)).toBeTruthy()
    })
    it("equalsNoneOf", () => {
        const isOneOrZero = new NumberValidator().equalsNoneOf(0, 1).seal()
        expect(isOneOrZero("10")).toBeFalsy()
        expect(isOneOrZero(0)).toBeFalsy()
        expect(isOneOrZero(1)).toBeFalsy()
        expect(isOneOrZero(1.1)).toBeTruthy()
        expect(isOneOrZero(5)).toBeTruthy()
        expect(isOneOrZero(10)).toBeTruthy()
    })
    it("equalsOneOf", () => {
        const isOneOrZero = new NumberValidator().equalsOneOf(0, 1).seal()
        expect(isOneOrZero("10")).toBeFalsy()
        expect(isOneOrZero(10)).toBeFalsy()
        expect(isOneOrZero(1.1)).toBeFalsy()
        expect(isOneOrZero(0)).toBeTruthy()
        expect(isOneOrZero(1)).toBeTruthy()
    })
    it("greaterThan", () => {
        const isGreaterThanZero = new NumberValidator().greaterThan(0).seal()
        expect(isGreaterThanZero("abc")).toBeFalsy()
        expect(isGreaterThanZero(0)).toBeFalsy()
        expect(isGreaterThanZero(1)).toBeTruthy()
    })
    it("greaterThanOrEqual", () => {
        const isGreaterThanZero = new NumberValidator().greaterThanOrEqual(0).seal()
        expect(isGreaterThanZero("abc")).toBeFalsy()
        expect(isGreaterThanZero(-1)).toBeFalsy()
        expect(isGreaterThanZero(0)).toBeTruthy()
        expect(isGreaterThanZero(1)).toBeTruthy()
    })
    it("isInt", () => {
        const isInt = new NumberValidator().isInt().seal()
        expect(isInt("abc")).toBeFalsy()
        expect(isInt("123")).toBeFalsy()
        expect(isInt(1.23)).toBeFalsy()
        expect(isInt(123)).toBeTruthy()
    })
    it("isFloat", () => {
        const isFloat = new NumberValidator().isFloat().seal()
        expect(isFloat("abc")).toBeFalsy()
        expect(isFloat("123")).toBeFalsy()
        expect(isFloat(123)).toBeFalsy()
        expect(isFloat(1.23)).toBeTruthy()
    })
    it("lessThan", () => {
        const isLessThanZero = new NumberValidator().lessThan(0).seal()
        expect(isLessThanZero("abc")).toBeFalsy()
        expect(isLessThanZero(1)).toBeFalsy()
        expect(isLessThanZero(0)).toBeFalsy()
        expect(isLessThanZero(-1)).toBeTruthy()
    })
    it("lessThanOrEqual", () => {
        const isLessThanZero = new NumberValidator().lessThanOrEqual(0).seal()
        expect(isLessThanZero("abc")).toBeFalsy()
        expect(isLessThanZero(1)).toBeFalsy()
        expect(isLessThanZero(0)).toBeTruthy()
        expect(isLessThanZero(-1)).toBeTruthy()
    })
})
